# Generated by Django 3.2.13 on 2023-12-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('shortdescription', models.CharField(max_length=300)),
                ('pricepernight', models.CharField(max_length=30)),
                ('longdescription', models.CharField(max_length=1000)),
                ('amenities', models.CharField(max_length=300)),
            ],
        ),
    ]
