# Generated by Django 3.2.13 on 2023-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=models.SlugField(default='placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(default='Placeholder'),
        ),
    ]
