# Generated by Django 3.2.13 on 2024-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0003_alter_listing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferences',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
