# Generated by Django 3.2.13 on 2024-01-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0004_auto_20240101_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slug',
        ),
    ]
