# Generated by Django 3.2.13 on 2024-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0009_alter_booking_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='listing',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=0),
        ),
    ]
