# Generated by Django 3.2.13 on 2024-01-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
