# Generated by Django 3.2.13 on 2024-01-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0013_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='detailedimage',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
