# Generated by Django 3.2.13 on 2024-01-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0014_listing_detailedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='xcoordinate',
            field=models.IntegerField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='ycoordinate',
            field=models.IntegerField(default=None, max_length=30),
        ),
    ]
