# Generated by Django 3.2.13 on 2024-01-05 11:38

import Tomato.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0016_auto_20240105_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=0, validators=[Tomato.models.validate_zero]),
        ),
    ]
