# Generated by Django 3.2.13 on 2024-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0017_alter_booking_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
