# Generated by Django 3.2.13 on 2024-01-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0019_alter_listing_pricepernight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pricepernight',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
