# Generated by Django 3.2.13 on 2024-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tomato', '0021_alter_listing_pricepernight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
    ]
